sonar.projectKey=daemon1s_riftjournal-riot-fastapi-nextjs-postgres
sonar.organization=daemon1s
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=**/*.test.tsx,**/test_*.py
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.coverage.exclusions=**/*
